version: "3"
services:
  proxy:
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    command: /bin/bash -c "envsubst '$$HOSTNAME $$AUTH_TOKEN $$REGISTRY_URL' < /etc/nginx/conf.d/upm-proxy.conf.template > /etc/nginx/conf.d/upm-proxy.conf && exec nginx -g 'daemon off;'"
    restart: always
